### PR TITLE
Removed UTF-8 tag and added yr.no

### PR DESCRIPTION
**Pull request by snaggen**
Hi, The UTF-8 tag seems to break the translations, so I have added a version of the preferences without that (and that solved the problem) and I also added the yr.no to the provider list.

### CODE REVIEW

**Comment by kylewlacy** [comment]
What problem was there with the UTF-8 `<meta>` tag?

On iOS, there's a problem with Unicode characters displaying in the language dropdown, but removing the `<meta>` tag doesn't seem to have any effect on that.

**Comment by snaggen** [comment]
If the meta charset UTF-8 was present, the whole date line on the watchface was not shown at all (if they contained non ascii chars). I guess that it caused the translations to be sent in the wrong encoding somehow. I haven't tried to debug this at all, so I don't have any deeper insights.

**Comment by kylewlacy** [comment]
I manually removed the `<meta>` tag in commit 027c59be0773daafceae77479ba676e55c8d30a2, as well as escaped the Unicode characters through the JavaScript (which fixes the issue that I posted on the [Pebble forums](http://forums.getpebble.com/discussion/10721)).

Could you check out the [`yr-no` branch](https://github.com/kylewlacy/futura-weather-redux/tree/yr-no) and confirm that it fixes your issue? The translations work fine for me (although I'm on iOS).

**Comment by snaggen** [comment]
Yes, it works. So it should be safe to bring in to master.

**Comment by snaggen** [comment]
The utf-8 is commited and yr.no have its own issue, so I'm closing this one.

**Pull request closed without merging**
